apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend-prod
  labels:
    app: springboot-backend
    env: prod
spec:
  replicas: 1   # Multiple pods for high availability
  selector:
    matchLabels:
      app: springboot-backend
      env: prod
  template:
    metadata:
      labels:
        app: springboot-backend
        env: prod
    spec:
      containers:
        - name: springboot-backend
          image:  <ACR_NAME>.azurecr.io/<IMAGE_NAME>:<TAG>   # ACR image
          ports:
            - containerPort: 8080
#          resources:
#            requests:
#              cpu: "250m"
#              memory: "512Mi"
#            limits:
#              cpu: "500m"
#              memory: "1Gi"
          env:
            # === Database connection variables ===
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: azure-postgres-secret-prod
                  key: DB_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: azure-postgres-secret-prod
                  key: DB_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-postgres-secret-prod
                  key: DB_PASSWORD

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # === JWT secret key ===
            - name: SPRING_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-dev
                  key: JWT_SECRET_KEY

            # === Mail configuration ===
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret-dev
                  key: MAIL_USERNAME

            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret-dev
                  key: MAIL_PASSWORD

            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"

            - name: SPRING_MAIL_PORT
              value: "587"

            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"

            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"

              #===active profile defining===

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"


