apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-service-dev
  labels:
    app: springboot-backend
    env: k-dev
spec:
  type: NodePort   # You can also use ClusterIP if no external access is needed
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: springboot-backend
    env: k-dev
