trigger:
  branches:
    include:
      - main

resources:
  pipelines:
    - pipeline: backend-ci
      source: backend-ci
      trigger:
        branches:
          include:
            - main

variables:
  azureServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  aksCluster: "aks-banking-cluster"
  namespace: "default"
  deploymentFile: "kubernetes/prod/deployment.yaml"
  secretFile: "kubernetes/prod/secret.yaml"
  acrName: "acrbankingapp"
  imageName: "backend"
  imageTag: "$(Build.BuildId)"
  keyVaultName: "kv-banking-app"

stages:
  - stage: Deploy
    displayName: "Deploy Backend to AKS"
    jobs:
      - job: DeployToAKS
        pool:
          name: Default

        steps:
          - checkout: self

          # Fetch all secrets from Key Vault
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              KeyVaultName: "$(keyVaultName)"
              SecretsFilter: '*'
              RunAsPreJob: false
            displayName: "Fetch Secrets from Azure Key Vault"

          # Replace placeholders in secret YAML
          - powershell: |
              Write-Host "Injecting secrets into YAML..."
              $secretFile = "$(secretFile)"
              $deploymentFile = "$(deploymentFile)"
              
              $DB_USER = $env:DB_USER
              $DB_PASSWORD = $env:DB_PASSWORD
              $DB_NAME = $env:DB_NAME
              $MAIL_USERNAME = $env:MAIL_USERNAME
              $MAIL_PASSWORD = $env:MAIL_PASSWORD
              $JWT_SECRET_KEY = $env:JWT_SECRET_KEY
              $ACR_NAME = "$(acrName)"
              $IMAGE_NAME = "$(imageName)"
              $IMAGE_TAG = "$(imageTag)"

              (Get-Content $secretFile) `
                -replace "<DB_USER>", $DB_USER `
                -replace "<DB_PASSWORD>", $DB_PASSWORD `
                -replace "<DB_NAME>", $DB_NAME `
                -replace "<MAIL_USERNAME>", $MAIL_USERNAME `
                -replace "<MAIL_PASSWORD>", $MAIL_PASSWORD `
                -replace "<JWT_SECRET_KEY>", $JWT_SECRET_KEY | Set-Content $secretFile
            displayName: "Replace Secret Placeholders"

              # Replace ACR details in deployment.yaml
              (Get-Content $deploymentFile) `
                -replace "<ACR_NAME>", $ACR_NAME `
                -replace "<IMAGE_NAME>", $IMAGE_NAME `
                -replace "<TAG>", $IMAGE_TAG | Set-Content $deploymentFile
             displayName: "Replace Deployment Placeholders"

          # Deploy to AKS using PowerShell script
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              ScriptType: 'FilePath'
              ScriptPath: './Pipelines/Backend-CD.ps1'
              ScriptArguments: '$(resourceGroup) $(aksCluster) $(namespace) $(deploymentFile) $(secretFile) $(acrName) $(imageName) $(imageTag)'
              azurePowerShellVersion: 'LatestVersion'
            displayName: "Deploy Backend to AKS"
