#trigger:
#  branches:
#    include:
#      - main

resources:
  pipelines:
    - pipeline: backendCI
      source: backend-ci
      trigger:
        branches:
          include:
            - main

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  aksCluster: "bankcluster"
  namespace: "default"
  deploymentFile: "kubernetes/prod/deployment.yaml"
  secretFile: "kubernetes/prod/secret.yaml"
  acrName: "bankingacr"
  imageName: "backend-ci"
  imageTag: "$(resources.pipeline.backendCI.runId)"


  # Secret pipeline variables (mark as secret in Azure DevOps UI)
  # DB_USER, DB_PASSWORD, DB_URL, MAIL_USERNAME, MAIL_PASSWORD, JWT_SECRET_KEY

stages:
  - stage: Deploy
    displayName: "Deploy Backend to AKS"
    jobs:
      - job: DeployToAKS
        pool:
          name: Default
        steps:
          - checkout: self

          # Replace tokens in secret.yaml using pipeline variables
          - powershell: |
              Write-Host "Replacing tokens in secret.yaml using pipeline variables..."
              $secretFile = "$(secretFile)"

              (Get-Content $secretFile -Raw) `
                -replace "<DB_USER>", "$(DB_USER)" `
                -replace "<DB_PASSWORD>", "$(DB_PASSWORD)" `
                -replace "<DB_URL>", "$(DB_URL)" `
                -replace "<MAIL_USERNAME>", "$(MAIL_USERNAME)" `
                -replace "<MAIL_PASSWORD>", "$(MAIL_PASSWORD)" `
                -replace "<JWT_SECRET_KEY>", "$(JWT_SECRET_KEY)" |
                Set-Content $secretFile -Force

              Write-Host "Token replacement complete for $secretFile"
            displayName: "Replace secrets in secret.yaml"

          # ----- NEW: Print secrets (for debugging) -----
          # WARNING: This will output secret values to the pipeline log.
          # If variables are marked secret in Azure DevOps they will be masked in the log,
          # but avoid leaving this step in production pipelines.
          - powershell: |
              Write-Host "Printing secrets (they should be masked if marked secret in pipeline settings)..."
              Write-Host "DB_USER = $(DB_USER)"
              Write-Host "DB_PASSWORD = $(DB_PASSWORD)"
              Write-Host "DB_URL = $(DB_URL)"
              Write-Host "MAIL_USERNAME = $(MAIL_USERNAME)"
              Write-Host "MAIL_PASSWORD = $(MAIL_PASSWORD)"
              Write-Host "JWT_SECRET_KEY = $(JWT_SECRET_KEY)"
              Write-Host "Finished printing secrets."
            displayName: "Print secrets (DEBUG) - REMOVE AFTER DEBUGGING"

          # Get AKS credentials
          - task: AzureCLI@2
            displayName: "Get AKS credentials"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster) --overwrite-existing

          # Apply secret.yaml to AKS
          - task: Kubernetes@1
            displayName: "Apply secret.yaml to AKS"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              azureSubscriptionEndpoint: "$(myServiceConnection)"
              connectionType: "Azure Resource Manager"
              azureResourceGroup: "$(resourceGroup)"
              kubernetesCluster: "$(aksCluster)"
              command: "apply"
              useConfigurationFile: true
              configuration: "$(secretFile)"

          # Replace image details in deployment YAML
          - powershell: |
              Write-Host "Replacing image placeholders in deployment YAML..."
              $deploymentFile = "$(deploymentFile)"
              $ACR_NAME = "$(acrName)"
              $IMAGE_NAME = "$(imageName)"
              $IMAGE_TAG = "$(imageTag)"

              (Get-Content $deploymentFile -Raw) `
                -replace "<ACR_NAME>", $ACR_NAME `
                -replace "<IMAGE_NAME>", $IMAGE_NAME `
                -replace "<TAG>", $IMAGE_TAG |
                Set-Content $deploymentFile -Force

              Write-Host "Replaced image details in $deploymentFile"
            displayName: "Replace Secret & Deployment Placeholders"

          # Deploy backend to AKS via PowerShell
          - task: AzurePowerShell@5
            displayName: "Deploy Backend to AKS"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              ScriptType: "FilePath"
              ScriptPath: "./Pipelines/Backend-CD.ps1"
              ScriptArguments: "$(resourceGroup) $(aksCluster) $(namespace) $(deploymentFile) $(secretFile) $(acrName) $(imageName) $(imageTag)"
              azurePowerShellVersion: "LatestVersion"
