trigger:
  branches:
    include:
      - main

variables:
  System.Debug: true       # Enable detailed logs
  acrName: "acrbankingapp"
  imageName: "backend"
  dockerfilePath: "Dockerfile"
  imageTag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: "CI - Build & Push Docker Image"
    jobs:
      - job: BuildAndPush
        displayName: "Build & Push Docker Image Job"
        pool:
          name: Default
          demands:
            - docker
        steps:
          - checkout: self

          # Run the Bash script
          - task: Bash@3
            displayName: "Build & Push Docker Image"
            inputs:
              filePath: './ci-build-and-push.sh'
              arguments: '$(acrName) $(imageName) $(dockerfilePath) $(imageTag)'
              workingDirectory: '$(Build.SourcesDirectory)'
              failOnStderr: false