trigger:
  branches:
    include:
      - main

resources:
  pipelines:
    - pipeline: backend-ci
      source: backend-ci
      trigger:
        branches:
          include:
            - main

variables:
  azureServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  aksCluster: "aks-banking-cluster"
  namespace: "default"
  deploymentFile: "kubernetes/prod/deployment.yaml"
  secretFile: "kubernetes/prod/secret.yaml"
  acrName: "acrbankingapp"
  imageName: "backend-CI"
  imageTag: "v1"
  keyVaultName: "kv-banking-app"

stages:
  - stage: Deploy
    displayName: "Deploy Backend to AKS"
    jobs:
      - job: DeployToAKS
        pool:
          vmImage: "windows-latest"
        steps:
          - checkout: self

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              KeyVaultName: "$(keyVaultName)"
              SecretsFilter: '*'
              RunAsPreJob: false
            displayName: "Fetch Secrets from Azure Key Vault"

          - powershell: |
              Write-Host "Injecting secrets into YAML..."
              (Get-Content "$(secretFile)") `
                  -replace "<DB_USER>", "$(DB_USER)" `
                  -replace "<DB_PASSWORD>", "$(DB_PASSWORD)" `
                  -replace "<DB_NAME>", "$(DB_NAME)" `
                  -replace "<MAIL_USERNAME>", "$(MAIL_USERNAME)" `
                  -replace "<MAIL_PASSWORD>", "$(MAIL_PASSWORD)" `
                  -replace "<JWT_SECRET_KEY>", "$(JWT_SECRET_KEY)" | Set-Content "$(secretFile)"
              displayName: "Replace Secret Placeholders"

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: 'FilePath'
              scriptLocation: scriptPath
              scriptPath: "'$(Build.SourcesDirectory)/Backend-CD.ps1"
              arguments: "$(resourceGroup) $(aksCluster) $(namespace) $(deploymentFile) $(secretFile) $(acrName) $(imageName) $(imageTag)"
            displayName: "Deploy Backend to AKS"
